# some defaults
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# list of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'thewtex/tmux-mem-cpu-load'

set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text "#(~/.tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load -g0 --interval 2)"

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

